
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: heron-apiserver
  name: heron-apiserver
  namespace: default


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heron-apiserver
  labels:
    k8s-app: heron-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: heron-apiserver
  namespace: default
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: heron-apiserver
  name: heron-apiserver
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: heron-apiserver
  replicas: 1
  template:
    metadata:
      labels:
        app: heron-apiserver
        component: apiserver
        k8s-app: heron-apiserver
    spec:
      serviceAccountName: heron-apiserver
      containers:
        - name: heron-apiserver
          image: streamlio/streamlio:0.1
          command: ["sh", "-c"]
          args:
            - >-
              heron-apiserver
              --base-template kubernetes
              --cluster kubernetes
              -D heron.statemgr.connection.string=zookeeper:2181
              -D heron.kubernetes.scheduler.uri=http://localhost:8001
              -D heron.executor.docker.image=streamlio/streamlio:0.1
              -D heron.uploader.dlog.topologies.num.replicas=1
              -D heron.class.uploader=com.twitter.heron.uploader.dlog.DLUploader
              -D heron.uploader.dlog.topologies.namespace.uri=distributedlog://zookeeper:2181/distributedlog
        - name: kubectl-proxy
          image: streamlio/kubectl:1.7.5
          command: ["sh", "-c"]
          args:
            - >
              kubectl proxy -p 8001 --v=8
---    
apiVersion: v1
kind: Service
metadata:
  name: heron-apiserver
spec:
  selector:
    app: heron-apiserver
    k8s-app: heron-apiserver
    component: apiserver
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort