##
## Deployment Pod for tracker and ui
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heron-tracker
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: heron-tracker
    spec:
      containers:
        - name: heron-tracker
          image: streamlio/streamlio:0.1
          #imagePullPolicy: Never
          ports:
            - containerPort: 8888
              name: api-port
          command: ["sh", "-c"]
          args:
            - >-
              heron-tracker 
              --type=zookeeper
              --name=kubernetes 
              --hostport=zookeeper:2181
              --rootpath="/heron" 
              --verbose
        - name: heron-ui
          image: streamlio/streamlio:0.1
          #imagePullPolicy: Never
          ports:
            - containerPort: 8889
              name: app-port
          command: ["sh", "-c"]
          args:
            - >-
              heron-ui

---

##
##
##
apiVersion: v1
kind: Service
metadata:
  name: heron-ui
spec:
  selector:
    app: heron-tracker
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
  type: NodePort
